version: '3.8'

services:
#   ecommerce:
#        build:
#            context: ../..
#            dockerfile: ./e-commerce-engineering/dockerfile
#        image: ecommerce.engineering.web:latest
#        container_name: ecommerce.engineering.web:latest
#        ports:
#          - "5002:5002"
#        networks:
#          - dev-default

  mysql:
    image: mysql:8.0
    container_name: as-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-default

  redis:
    image: redis:latest
    container_name: as-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-default
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysql_data:
  redis_data:

networks:
  my_network:
    driver: bridge




