services:
  mysql:
    image: mysql:8.0
    container_name: as-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: usermysql
      MYSQL_PASSWORD: passmysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-default

  redis:
    image: redis:latest
    container_name: as-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-default
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "root"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "my_secure_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  redis_data:

networks:
  dev-default:
    driver: bridge




